name: Playwright tests

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      url:
        description: The deployment url
        value: ${{ jobs.deploy.outputs.url }}
    secrets:
      VERCEL_API_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: true

jobs:
  deploy:
    name: Deploy to Vercel
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      PROD_FLAG: "${{ inputs.environment == 'production' && '--prod' || '' }}"
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Reset PR message
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            "${{ env.STATUS == 'failed' && 'Deploy Failed' || env.MESSAGE }}"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install
        run: npm ci
      - name: Build and deploy
        id: deploy
        run: |
          npx vercel pull --yes --environment=${{ env.ENVIRONMENT }} --scope=${{ vars.VERCEL_SCOPE }} --token=${{ secrets.VERCEL_API_TOKEN }} .env.local
          npx vercel build ${{ env.PROD_FLAG }} --scope=${{ vars.VERCEL_SCOPE }} --token=${{ secrets.VERCEL_API_TOKEN }}
          echo "url=$(npx vercel deploy --prebuilt ${{ env.PROD_FLAG }} --scope=${{ vars.VERCEL_SCOPE }} --token=${{ secrets.VERCEL_API_TOKEN }})" >> "$GITHUB_OUTPUT"
